# Generated by Django 4.2.3 on 2023-07-13 09:15

import certificates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to=certificates.models.certificate_image_upload_path),
        ),
    ]
